# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('slot', models.IntegerField()),
                ('initial_defense', models.CharField(max_length=16)),
                ('max_defense', models.CharField(max_length=16)),
                ('fire_resistance', models.IntegerField()),
                ('water_resistance', models.IntegerField()),
                ('thunder_resistance', models.IntegerField()),
                ('ice_resistance', models.IntegerField()),
                ('dragon_resistance', models.IntegerField()),
            ],
            options={
                'db_table': 'armor',
            },
        ),
        migrations.CreateModel(
            name='ArmorSeries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('rare', models.CharField(max_length=32)),
                ('initial_defense', models.CharField(max_length=16)),
                ('max_defense', models.CharField(max_length=16)),
                ('slot', models.IntegerField()),
                ('fire_resistance', models.IntegerField()),
                ('water_resistance', models.IntegerField()),
                ('thunder_resistance', models.IntegerField()),
                ('ice_resistance', models.IntegerField()),
                ('dragon_resistance', models.IntegerField()),
            ],
            options={
                'db_table': 'armor_series',
            },
        ),
        migrations.CreateModel(
            name='ArmorSeriesSkillPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('armor_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.ArmorSeries')),
            ],
            options={
                'db_table': 'armor_series_skill_point',
            },
        ),
        migrations.CreateModel(
            name='ArmorSkillPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.Armor')),
            ],
            options={
                'db_table': 'armor_skill_point',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('require_point', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='SkillSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'skill_system',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.SkillSystem'),
        ),
        migrations.AddField(
            model_name='armorskillpoint',
            name='skill_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.SkillSystem'),
        ),
        migrations.AddField(
            model_name='armorseriesskillpoint',
            name='skill_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.SkillSystem'),
        ),
        migrations.AddField(
            model_name='armorseries',
            name='skills',
            field=models.ManyToManyField(to='monhan.Skill'),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monhan.ArmorSeries'),
        ),
    ]
